library(COSG)
# devtools::install_github('genecell/COSGR')
library(harmony)
library(BPCells)
library(Seurat)
library(SeuratObject)
library(SeuratDisk)
library(ggsci)
library(dplyr) 
library(future)
library(Seurat)
library(clustree)
library(cowplot)
library(data.table)
library(dplyr)
library(ggplot2)
library(patchwork)
library(stringr)
library(scRNAstat) 
library(clustree)
library(cowplot)
library(stringr)
library(patchwork)
library(rliger)
library(RColorBrewer)
library(tidyverse)
library(reshape2)
library(ggsci)
library(ggstatsplot)
# 多线程
library(future)
# check the current active plan
plan()
# change the current plan to access parallelization
plan("multicore", workers = 8)
options(future.globals.maxSize = 8000 * 1024^2)
plan()
